### ISSUE TITLE
Sagan's Second Contribution

### ISSUE THREAD

**Issue by PrivateCaller** [mlhaus/Open-Source-2023-tue-night#26]
Map1 - [mapAB4](https://codingbat.com/prob/p136950)
Map2 - [wordMultiple](https://codingbat.com/prob/p190862)

**Comment by kiranrokkam09** [comment]
@PrivateCaller what should I do in this issue?

**Comment by mlhaus** [comment]
@kiranrokkam09 This repo is for students who were given an assignment. I am not accepting pull requests from anyone else.
